name: "ci"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        vim_type: ["Neovim"]
        vim_version: ["head", "stable"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: notomo/action-setup-nvim-lua@v1

      - name: "Install vusted"
        run: "luarocks --lua-version=5.1 install vusted"

      - name: "Setup Vim"
        id: "vim"
        uses: "thinca/action-setup-vim@v1"
        with:
          vim_version: "${{ matrix.vim_version }}"
          vim_type: "${{ matrix.vim_type }}"

      - name: "Lint"
        uses: "JohnnyMorganz/stylua-action@v2"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .

      - name: "Show Vim version"
        run: ${{ steps.vim.outputs.executable }} --version

      - name: "Test"
        run: make test
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
